module.exports = {
  apps: [
    {
      name: "fern",
      script: "dist/index.js",
      node_args: "--env-file=.env",
      autorestart: true,
      max_restarts: 15,
      min_uptime: "10s",
      restart_delay: 5000,
      error_file: "logs/fern-error.log",
      out_file: "logs/fern-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss.SSS",
      merge_logs: true,
      env: {
        NODE_ENV: "production",
      },
    },
    {
      name: "caffeinate",
      script: "caffeinate",
      args: "-s",
      autorestart: true,
      interpreter: "none",
      error_file: "logs/caffeinate-error.log",
      out_file: "logs/caffeinate-out.log",
    },
    {
      name: "fern-updater",
      script: "scripts/updater.sh",
      interpreter: "bash",
      autorestart: true,
      max_restarts: 10,
      min_uptime: "5s",
      restart_delay: 3000,
      error_file: "logs/updater-error.log",
      out_file: "logs/updater-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss.SSS",
      merge_logs: true,
    },
    {
      name: "ngrok",
      script: "ngrok",
      args: "http 4000 --domain biconically-unconducive-travis.ngrok-free.dev",
      autorestart: true,
      interpreter: "none",
      error_file: "logs/ngrok-error.log",
      out_file: "logs/ngrok-out.log",
    },
  ],
};
